### ISSUE TITLE
PLEASE HELP ME FTO SETUP

### ISSUE THREAD

**Issue by s6287** [ankitgoyal0301/Homemade-RecipeBowl-Your-Ingredients-Our-Recipes#3]
Error on request:
Traceback (most recent call last):
  File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\venv\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\venv\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\app.py", line 58, in <module>
    dataset_raw = load_dataset(True)
  File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\app.py", line 37, in load_dataset
    with open(dataset_file_path) as dataset_file:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/datasets/recipes_raw_nosource_ar.json'

**Comment by Mansijain0507** [comment]
> Error on request: Traceback (most recent call last): File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\venv\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi execute(self.server.app) File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\venv\Lib\site-packages\werkzeug\serving.py", line 312, in execute application_iter = app(environ, start_response) File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\app.py", line 58, in dataset_raw = load_dataset(True) File "D:\SEM VI PROJECT\Homemade-RecipeBowl-Your-Ingredients-Our-Recipes\ui\api\app.py", line 37, in load_dataset with open(dataset_file_path) as dataset_file: FileNotFoundError: [Errno 2] No such file or directory: 'tmp/datasets/recipes_raw_nosource_ar.json'

i also faced the same issue
